---
title: "The adam_db Argument"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{The adam_db Argument}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Introduction 

We have decided to use the `dm` package in `chevron` to model the data relations of the CDISC ADaM datasets. In this
vignette we introduce how we intend to use


The `dm` R package models relational dataset as found in relational databases. The CDISC standard is a relational data
standard and w


```{r}
library(chevron)
syn_data <- syn_test_data()[c("adsl", "adae", "adlb")]

drop_adsl_vars <- function(adsl, adam) {
  adam[ c("USUBJID", "STUDYID", setdiff(names(adam), names(adsl)))]
}


adsl <- syn_data$adsl
adae <- syn_data$adae
adlb <- syn_data$adlb

adam_study_data <- dm(adsl = adsl, adae = drop_adsl_vars(adsl, adae), adlb = drop_adsl_vars(adsl, adlb)) %>%
  dm_add_pk(adsl, c("USUBJID", "STUDYID")) %>%
  dm_add_fk(adae, c("USUBJID", "STUDYID"), ref_table = "adsl") %>%
  dm_add_pk(adae, c("USUBJID", "STUDYID", "ASTDTM", "AETERM", "AESEQ")) %>%
  dm_add_fk(adlb, c("USUBJID", "STUDYID"), ref_table = "adsl") %>%
  dm_add_pk(adlb, c("STUDYID", "USUBJID", "PARAMCD", "BASETYPE", "AVISITN", "ATPTN", "DTYPE", "ADTM", "LBSEQ", "ASPID"))

adam_study_data

adam_db %>%
  dm_get_table_with_additional_vars(adae, "ARM", "ARMCD")


markup_funs <- tribble(
  ~dataname, ~varname, ~mapper,
  "adsl",    "ARM",    c("PLACEBO" = "Placebo", ...)
)
dm_get_tabl_all_vars(adae )

```
