name: New Table
description: Request a new table template

body:

- type: markdown
  attributes:
    value: "Please describe the characteristics of the required table"

- type: input
  id: table_name
  attributes:
    label: "Table Name"
    description: "Standard name of the table"
    placeholder: "ex. AET02"


- type: input
  id: table_pupose
  attributes:
    label: "Description"
    description: "Details on the generic purpose of the table"
    placeholder: "ex. an adverse event table"

- type: input
  id: analysis_dataset
  attributes:
    label: "Analysis dataset"
    description: "Name of the standard dataset input"
    placeholder: "ex. ADAE"

- type: textarea
  id: analysis_filtering
  attributes:
    label: "Analysis filtering"
    description: "Filtering criteria of the input"
    value: "ex. ANL01FL = Y"

- type: textarea
  id: analysis_population
  attributes:
    label: "Analysis population"
    description: "The selected population, typically SE, AP or IT"
    value: "ex. SE"

- type: textarea
  id: column_variables
  attributes:
    label: "Column Variable"
    description: "Names of the columns in the input dataset used to split the table"
    value: "ex. ACTARM"

- type: textarea
  id: analysis_variables
  attributes:
    label: "Analysis variables"
    description: "The name of the spliting variables in hierarchical order"
    value: "ex. AEBODSYS, AEDECOD, ASEV \n
            ex. 1. AEBODSYS 2. AEDECOD 3. ASEV"

- type: textarea
  id: analysis_concept
  attributes:
    label: "Analysis concept"
    description: "An alternative description for summary tables similar to AET01"
    value: "ex. \n - Serious AE
                \n - Related AE
                \n - Total number of AEs"


- type: textarea
  id: statistics
  attributes:
    label: "Statistics"
    description: "A Description of the statistical procedure"
    value: "ex. Frequency count and % (based on N)"

- type: dropdown
  id: remove_0
  attributes:
    label: "Default treatment of zero count rows"
    multiple: false
    options:
      - "Remove zero count rows by default"
      - "Keep zero count rows by default"
      - "Always ask for user input"
      - "Not applicable / Other"

- type: textarea
  id: comments
  attributes:
    label: "Additional comments"
    value: "ex. Some additional details"
